### ISSUE TITLE
Better preview

### ISSUE THREAD

**Issue by Amparose** [vicro/BlenderQuickLook#1]
Hey, great work! Built, installed, and works on OSX Yosemite. I did notice, however that actually Quicklooking just seems to zoom the thumbnail rather than provide a proper preview. It would be great if it was a bigger image, or better, be like a Collada file Quicklook as it is a full interactive 3d view.

Anyway, I also found [this project](http://www.alecjacobson.com/weblog/?p=3604), which might give you some more ideas to push this along.

p.s. might be nice to provide the built QL file in the git repo so people don't have to fumble around in Xcode to get it.

**Comment by vicro** [comment]
Thanks for the comments. Yes the plugin right now just shows the embedded thumbnail in the blender file. Of course I would like to show the full 3D scene when showing the large preview. This would be indeed quite a task. Things that would need to be solved:
- parse the actual 3D data
- decide what to do with mesh modifiers,animations, shading, lights, cameras etc etc
- render to screen

I will try to include a compiled QL file when I have some spare time.
