### ISSUE TITLE
Can you Provide a Binary for Ease of Install

### ISSUE THREAD

**Issue by owlboy** [vicro/BlenderQuickLook#2]
Hello,

Just a small request for a version that is complied and ready to install.

**Comment by vicro** [comment]
I'll look into it, can't give a specific date sorry.

**Comment by vicro** [comment]
I uploaded a compiled file to the releases page.
Sorry for the delays.
`https://github.com/vicro/BlenderQuickLook/releases/latest`
Please check it out.
